# Generated by Django 4.1.1 on 2022-12-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('adress', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='suites')),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('adress', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='suites')),
            ],
        ),
    ]
