# Generated by Django 4.1.4 on 2022-12-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0003_rename_author_name_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suites/suites'),
        ),
    ]
